name: epub-metadata
version: '4.6'
synopsis: Library for parsing epub document metadata
description: Library for parsing and manipulating epub document metadata. Supports epub versions 2 and 3. This library was constructed by studying the IDPF specifications for epub documents found here <http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm> and here <http://www.idpf.org/epub/30/spec/epub30-publications.html>
license: ISC
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
copyright: 2010-2020 Dino Morelli
category: Codec, Text
extra-source-files:
- changelog.md
- doc/dev/notes
- doc/hcar/epubmetadata-De.tex
- package.yaml
- README.md
- stack.yaml
# - testsuite/*.epub
# - testsuite/*.hs
# - testsuite/*.opf
# - testsuite/bookfiles/foo
# - testsuite/bookfiles/mimetype
# - testsuite/bookfiles/content/bar
# - testsuite/Epub2/*.hs
# - testsuite/Epub3/*.hs
- TODO.md
- util/show-opf.hs

github: dino-/epub-metadata

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.8 && < 5.0
- mtl

library:
  source-dirs: src/lib
  dependencies:
  - bytestring
  - utf8-string
  - containers
  - directory
  - filepath
  - hxt >= 9
  - regex-compat-tdfa
  - zip-archive

executables:
  epub-metadata-example:
    source-dirs: src/app
    main: epub-metadata-example.hs
    dependencies:
    - epub-metadata

tests:
  test-epub-metadata:
    source-dirs: src/tests
    main: test-main.hs
    dependencies:
      - directory
      - epub-metadata
      - filepath
      - HUnit
      - zip-archive
